name: Build Minecraft Client

# This tells GitHub to run the build whenever you push a change, 
# or when you manually click a "Run" button.
on:
  push:
    branches: [ master, main ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest # Uses a secure, temporary Linux server

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '2.7' # Changed this from 3.10 to 2.7 

      - name: Recompile Code
        run: python runtime/recompile.py

      - name: Reobfuscate Code
        run: python runtime/reobfuscate.py

      - name: Upload Finished Files
        uses: actions/upload-artifact@v4
        with:
          name: compiled-minecraft-classes
          path: reobf/
