name: Build Minecraft Client

on:
  push:
    branches: [ master, main ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-20.04 # Use an older server that still supports Python 2

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Install Python 2
        # We bypass the setup action and just force Linux to install Python 2 natively
        run: |
          sudo apt-get update
          sudo apt-get install -y python2
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python2 1

      - name: Recompile Code
        run: python runtime/recompile.py

      - name: Reobfuscate Code
        run: python runtime/reobfuscate.py

      - name: Upload Finished Files
        uses: actions/upload-artifact@v4
        with:
          name: compiled-minecraft-classes
          path: reobf/
