name: Build Minecraft Client

on:
  push:
    branches: [ master, main ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-22.04 # Use a currently supported GitHub server

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Install Python 2
        run: |
          sudo apt-get update
          sudo apt-get install -y python2

      - name: Recompile Code
        # We explicitly type 'python2' here so it doesn't accidentally use Python 3
        run: python2 runtime/recompile.py

      - name: Reobfuscate Code
        run: python2 runtime/reobfuscate.py

      - name: Upload Finished Files
        uses: actions/upload-artifact@v4
        with:
          name: compiled-minecraft-classes
          path: reobf/
